# Generated by Django 3.0.8 on 2020-07-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Startup', '0002_delete_live_investors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live_Investors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Investor', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
                ('Class_of_Share', models.CharField(max_length=20)),
                ('No_of_shares', models.IntegerField()),
                ('Percentage', models.IntegerField()),
                ('Price_per_Share', models.IntegerField()),
                ('Investment', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
    ]
