# Generated by Django 3.0.8 on 2020-07-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Startup', '0003_live_investors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_founders', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('Role_in_startup', models.CharField(max_length=20)),
                ('Email_address', models.EmailField(max_length=254)),
                ('Contact_no', models.IntegerField()),
                ('LinkedIn_profile', models.EmailField(max_length=254)),
            ],
        ),
    ]
