# Generated by Django 3.0.8 on 2020-07-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Startup', '0005_startup_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Financials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('How_much_money_have_you_raised_till_date_in_Lakhs', models.IntegerField()),
                ('How_much_debt_does_your_company_have_in_Lakhs', models.IntegerField()),
                ('Upload_company_financial_report_preferably_audited', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Funding_Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Minimum_Company_valuation', models.IntegerField()),
                ('Minimum_Cost_per_share', models.IntegerField()),
                ('Minimum_total_amount_for_investor_to_invest', models.IntegerField()),
                ('Other_requirements', models.CharField(max_length=20)),
            ],
        ),
    ]
