# Generated by Django 3.0.8 on 2020-07-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Startup', '0006_company_financials_funding_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_of_Investor', models.CharField(max_length=20)),
                ('Name_of_investor', models.CharField(max_length=20)),
                ('Total_amount_bid', models.IntegerField()),
                ('Percentage', models.IntegerField()),
                ('No_of_shares', models.IntegerField()),
                ('Price_per_share', models.IntegerField()),
                ('money_valuation', models.IntegerField()),
            ],
        ),
    ]
