# Generated by Django 3.0.8 on 2020-08-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Startup', '0007_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_amount_invested', models.IntegerField()),
                ('Percentage_of_cpmpany', models.IntegerField()),
                ('No_of_shares', models.IntegerField()),
                ('Price_per_share', models.IntegerField()),
                ('pre_or_post_money_valuation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Investor_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=20)),
                ('Date_of_birth', models.IntegerField()),
                ('Email_address', models.EmailField(max_length=254)),
                ('Contact_Number', models.IntegerField()),
            ],
        ),
    ]
