# Generated by Django 3.0.8 on 2020-08-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Startup', '0008_bids_investor_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=20)),
                ('add_or_change_profile_picture', models.IntegerField()),
                ('Email_address', models.EmailField(max_length=254)),
                ('change_password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Startup_Details1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Legal_Name_of_company', models.CharField(max_length=20)),
                ('Startup_Name', models.CharField(max_length=20)),
                ('Founding_month_and_year', models.IntegerField()),
                ('Location', models.CharField(max_length=20)),
                ('Sector', models.IntegerField()),
                ('GST_or_License_Number', models.IntegerField()),
                ('Administators_of_your_VC', models.IntegerField()),
                ('Employees_of_your_VC', models.IntegerField()),
                ('Startup_description', models.TextField()),
                ('Website_Link', models.TextField()),
            ],
        ),
    ]
