# Generated by Django 3.0.8 on 2020-08-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Startup', '0009_profile_startup_details1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Company_Bids',
        ),
        migrations.RenameField(
            model_name='company_bids',
            old_name='Percentage_of_cpmpany',
            new_name='Percentage_of_company',
        ),
    ]
