# Generated by Django 3.0.8 on 2020-08-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Startup', '0010_auto_20200817_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='add_or_change_profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
    ]
