# Generated by Django 3.0.8 on 2020-08-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Startup', '0012_auto_20200818_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup_details1',
            name='Website_Link',
            field=models.CharField(max_length=20),
        ),
    ]
