# Generated by Django 3.0.8 on 2020-08-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Startup', '0013_auto_20200819_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_of_membership', models.CharField(max_length=20)),
                ('Cost', models.CharField(max_length=20)),
                ('Duration', models.CharField(choices=[('1', 'monthly'), ('2', 'Quarterly'), ('3', 'Annual')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pay_now',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_on_Card', models.CharField(max_length=20)),
                ('Credit_card_number', models.IntegerField()),
                ('Exp_Month', models.CharField(max_length=20)),
                ('CVV', models.IntegerField()),
                ('Exp_Year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=20)),
                ('Description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile_or_Payment_Address', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UPIwallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Choose_your_wallet', models.CharField(choices=[('1', 'PayTM'), ('2', 'BHIM Axis Pay'), ('3', 'PhonePe'), ('4', 'Mobikwik'), ('5', 'Amazon Pay')], max_length=1)),
            ],
        ),
    ]
