# Generated by Django 3.0.8 on 2020-07-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0002_auto_20200723_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Company', models.CharField(max_length=20)),
                ('Percentage_of_company', models.IntegerField()),
                ('Type_of_shares', models.CharField(max_length=20)),
                ('No_of_shares', models.IntegerField()),
                ('Current_value', models.IntegerField()),
                ('Profit_or_loss_on_investment', models.IntegerField()),
                ('Amount_invested', models.IntegerField()),
            ],
            options={
                'db_table': 'Dashboard',
            },
        ),
    ]
