# Generated by Django 3.0.8 on 2020-07-27 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0003_dashboard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dashboard',
            new_name='Dashboard1',
        ),
        migrations.AlterModelTable(
            name='dashboard1',
            table='Dashboard1',
        ),
    ]
