# Generated by Django 3.0.8 on 2020-07-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0005_auto_20200728_2120'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dashboard1',
            table='Dashboard1',
        ),
    ]
