# Generated by Django 3.0.8 on 2020-07-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0006_auto_20200728_2121'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dashboard1',
            table=None,
        ),
    ]
