# Generated by Django 3.0.8 on 2020-07-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0007_auto_20200728_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_amount_to_invest', models.IntegerField()),
                ('Percentage_of_company', models.IntegerField()),
                ('No_of_shares', models.IntegerField()),
                ('Price_per_share', models.IntegerField()),
                ('Pre_money_valuation', models.IntegerField()),
            ],
        ),
    ]
