# Generated by Django 3.0.8 on 2020-07-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0009_investor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_Type', models.CharField(max_length=20)),
                ('Payment_Method', models.CharField(max_length=20)),
                ('Bank_Account_Number', models.IntegerField()),
                ('IFSC_code', models.IntegerField()),
            ],
        ),
    ]
