# Generated by Django 3.0.8 on 2020-07-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0010_account_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending_Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Investor', models.CharField(max_length=20)),
                ('Class_of_Share', models.CharField(max_length=20)),
                ('No_of_shares', models.IntegerField()),
                ('Percentage', models.IntegerField()),
                ('Price_per_share', models.IntegerField()),
                ('Total_Bid', models.IntegerField()),
                ('Status', models.FilePathField()),
            ],
        ),
    ]
