# Generated by Django 3.0.8 on 2020-07-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0011_pending_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_your_Ventrue_Capital_firm', models.CharField(max_length=20)),
                ('Location_of_your_Firm', models.CharField(max_length=20)),
                ('GST_or_Licencse_Number', models.IntegerField()),
                ('Your_website_Link', models.URLField()),
                ('Briefly_Describe_your_firms_Investments_and_expectations', models.TextField(max_length=20)),
                ('Administators_of_your_VC', models.IntegerField()),
                ('Employees_of_your_VC', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pending_Bid',
        ),
    ]
