# Generated by Django 3.0.8 on 2020-08-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0012_auto_20200730_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=20)),
                ('add_or_change_profile_picture', models.IntegerField()),
                ('Email_address', models.EmailField(max_length=254)),
                ('change_password', models.IntegerField()),
            ],
        ),
    ]
