# Generated by Django 3.0.8 on 2020-08-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0013_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='add_or_change_profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='Image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
