# Generated by Django 3.0.8 on 2020-08-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0014_auto_20200817_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
