# Generated by Django 3.0.8 on 2020-08-16 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0015_auto_20200817_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Image',
        ),
    ]
