# Generated by Django 3.0.8 on 2020-08-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0016_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
