# Generated by Django 3.0.8 on 2020-08-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0018_auto_20200817_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_details',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
