# Generated by Django 3.0.8 on 2020-08-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0019_auto_20200817_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Image',
            new_name='profile_picture',
        ),
    ]
