# Generated by Django 3.0.8 on 2020-08-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0020_auto_20200817_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_details',
            name='Administators_of_your_VC',
        ),
        migrations.RemoveField(
            model_name='company_details',
            name='Employees_of_your_VC',
        ),
    ]
