# Generated by Django 3.0.8 on 2020-08-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0023_subscription1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription1',
            name='Price',
            field=models.CharField(max_length=20),
        ),
    ]
