# Generated by Django 3.0.8 on 2020-08-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0024_auto_20200819_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription1',
            name='Description',
            field=models.TextField(max_length=100),
        ),
    ]
