# Generated by Django 3.0.8 on 2020-08-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0026_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Duration',
            field=models.CharField(choices=[('1', 'monthly'), ('2', 'Quarterly'), ('3', 'Annual')], max_length=1),
        ),
    ]
