# Generated by Django 3.0.8 on 2020-08-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0027_auto_20200819_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pey_now',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_on_Card', models.CharField(max_length=20)),
                ('Credit_card_number', models.IntegerField()),
                ('Exp_Month', models.CharField(choices=[('1', 'monthly'), ('2', 'Quarterly'), ('3', 'Annual')], max_length=1)),
                ('CVV', models.IntegerField()),
                ('Exp_Year', models.IntegerField()),
            ],
        ),
    ]
