# Generated by Django 3.0.8 on 2020-08-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0028_pey_now'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pey_now',
            new_name='Pay_now',
        ),
    ]
