# Generated by Django 3.0.8 on 2020-08-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0029_auto_20200820_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_now',
            name='Exp_Month',
            field=models.CharField(max_length=20),
        ),
    ]
