# Generated by Django 3.0.8 on 2020-08-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0032_upiwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Private_Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Select', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1)),
            ],
        ),
    ]
