# Generated by Django 3.0.8 on 2020-08-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0033_private_investor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Private_Investor',
        ),
    ]
