# Generated by Django 3.0.8 on 2020-08-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0034_delete_private_investor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VC_with_VCX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_VC', models.CharField(max_length=20)),
                ('Email_ID', models.EmailField(max_length=254)),
                ('Your_Name', models.CharField(max_length=20)),
                ('Your_email', models.EmailField(max_length=254)),
                ('Your_Designation', models.CharField(max_length=20)),
                ('Checkbox', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VC_without_VCX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_your_firm', models.CharField(max_length=20)),
                ('Location_of_your_firm', models.CharField(max_length=20)),
                ('GST_or_License_number', models.IntegerField()),
                ('Your_Name', models.CharField(max_length=20)),
                ('Your_email', models.EmailField(max_length=254)),
                ('Your_Designation', models.CharField(max_length=20)),
                ('Message', models.CharField(max_length=20)),
                ('Upload_GST_certificate', models.CharField(max_length=20)),
                ('Brief_Description_of_VC', models.CharField(max_length=20)),
                ('Website_Link', models.IntegerField()),
            ],
        ),
    ]
