# Generated by Django 3.0.8 on 2020-08-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0035_vc_with_vcx_vc_without_vcx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckBox1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Select', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CheckBox2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Select', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CheckBox3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
