# Generated by Django 3.0.8 on 2020-08-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0036_checkbox1_checkbox2_checkbox3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vc_with_vcx',
            name='Checkbox',
        ),
    ]
