# Generated by Django 3.0.8 on 2020-08-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0037_remove_vc_with_vcx_checkbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly_Reports1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Document', models.CharField(max_length=20)),
                ('File_Type', models.CharField(max_length=20)),
                ('Download_Link', models.URLField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='CheckBox1',
            new_name='CheckBox',
        ),
        migrations.RemoveField(
            model_name='vc_without_vcx',
            name='Message',
        ),
        migrations.AddField(
            model_name='vc_with_vcx',
            name='Undertaking_that_the_person_is_actually_the_part_of_the_VC_and_will_be_granted_access_only_if_the_admin_will_accept_your_request',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vc_without_vcx',
            name='Brief_Description_of_VC',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vc_without_vcx',
            name='Website_Link',
            field=models.CharField(max_length=20),
        ),
    ]
