# Generated by Django 3.0.8 on 2020-08-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0038_auto_20200830_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_reports1',
            name='Download_Link',
            field=models.URLField(),
        ),
    ]
