# Generated by Django 3.0.8 on 2020-08-31 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0039_auto_20200830_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='Name_of_Company',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='Type_of_shares',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dashboard1',
            name='Name_of_Company',
            field=models.TextField(max_length=20),
        ),
    ]
