# Generated by Django 3.0.8 on 2020-08-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0040_auto_20200831_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard1',
            name='Name_of_Company',
            field=models.CharField(max_length=20),
        ),
    ]
