# Generated by Django 3.0.8 on 2020-08-31 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0041_auto_20200831_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard1',
            name='Name_of_Company',
        ),
    ]
