# Generated by Django 3.0.8 on 2020-08-31 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0043_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
